# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utils/bounding_box.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ffn.utils import vector_pb2 as utils_dot_vector__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='utils/bounding_box.proto',
  package='ffn',
  syntax='proto2',
  serialized_pb=_b('\n\x18utils/bounding_box.proto\x12\x03\x66\x66n\x1a\x12utils/vector.proto\"\x7f\n\x0b\x42oundingBox\x12\"\n\x05start\x18\x01 \x01(\x0b\x32\x13.ffn.proto.Vector3j\x12!\n\x04size\x18\x02 \x01(\x0b\x32\x13.ffn.proto.Vector3j\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x14\n\x0cobject_label\x18\x04 \x01(\x04\".\n\rBoundingBoxes\x12\x1d\n\x03\x62ox\x18\x01 \x03(\x0b\x32\x10.ffn.BoundingBox')
  ,
  dependencies=[utils_dot_vector__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BOUNDINGBOX = _descriptor.Descriptor(
  name='BoundingBox',
  full_name='ffn.BoundingBox',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='ffn.BoundingBox.start', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size', full_name='ffn.BoundingBox.size', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='ffn.BoundingBox.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='object_label', full_name='ffn.BoundingBox.object_label', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=180,
)


_BOUNDINGBOXES = _descriptor.Descriptor(
  name='BoundingBoxes',
  full_name='ffn.BoundingBoxes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='box', full_name='ffn.BoundingBoxes.box', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=228,
)

_BOUNDINGBOX.fields_by_name['start'].message_type = utils_dot_vector__pb2._VECTOR3J
_BOUNDINGBOX.fields_by_name['size'].message_type = utils_dot_vector__pb2._VECTOR3J
_BOUNDINGBOXES.fields_by_name['box'].message_type = _BOUNDINGBOX
DESCRIPTOR.message_types_by_name['BoundingBox'] = _BOUNDINGBOX
DESCRIPTOR.message_types_by_name['BoundingBoxes'] = _BOUNDINGBOXES

BoundingBox = _reflection.GeneratedProtocolMessageType('BoundingBox', (_message.Message,), dict(
  DESCRIPTOR = _BOUNDINGBOX,
  __module__ = 'utils.bounding_box_pb2'
  # @@protoc_insertion_point(class_scope:ffn.BoundingBox)
  ))
_sym_db.RegisterMessage(BoundingBox)

BoundingBoxes = _reflection.GeneratedProtocolMessageType('BoundingBoxes', (_message.Message,), dict(
  DESCRIPTOR = _BOUNDINGBOXES,
  __module__ = 'utils.bounding_box_pb2'
  # @@protoc_insertion_point(class_scope:ffn.BoundingBoxes)
  ))
_sym_db.RegisterMessage(BoundingBoxes)


# @@protoc_insertion_point(module_scope)
