# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ffn/utils/bounding_box.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ffn/utils/bounding_box.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ffn.utils import vector_pb2 as ffn_dot_utils_dot_vector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x66\x66n/utils/bounding_box.proto\x12\x03\x66\x66n\x1a\x16\x66\x66n/utils/vector.proto\"\x7f\n\x0b\x42oundingBox\x12\"\n\x05start\x18\x01 \x01(\x0b\x32\x13.ffn.proto.Vector3j\x12!\n\x04size\x18\x02 \x01(\x0b\x32\x13.ffn.proto.Vector3j\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x14\n\x0cobject_label\x18\x04 \x01(\x04\".\n\rBoundingBoxes\x12\x1d\n\x03\x62ox\x18\x01 \x03(\x0b\x32\x10.ffn.BoundingBox')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ffn.utils.bounding_box_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOUNDINGBOX']._serialized_start=61
  _globals['_BOUNDINGBOX']._serialized_end=188
  _globals['_BOUNDINGBOXES']._serialized_start=190
  _globals['_BOUNDINGBOXES']._serialized_end=236
# @@protoc_insertion_point(module_scope)
