# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ffn/inference/consensus.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ffn/inference/consensus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ffn.utils import vector_pb2 as ffn_dot_utils_dot_vector__pb2
from ffn.inference import inference_pb2 as ffn_dot_inference_dot_inference__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x66\x66n/inference/consensus.proto\x12\x03\x66\x66n\x1a\x16\x66\x66n/utils/vector.proto\x1a\x1d\x66\x66n/inference/inference.proto\"\x84\x02\n\x10\x43onsensusRequest\x12.\n\rsegmentation1\x18\x01 \x01(\x0b\x32\x17.ffn.SegmentationSource\x12.\n\rsegmentation2\x18\x02 \x01(\x0b\x32\x17.ffn.SegmentationSource\x12\x1f\n\x17segmentation_output_dir\x18\x03 \x01(\t\x12\x31\n\x04type\x18\x04 \x01(\x0e\x32#.ffn.ConsensusRequest.ConsensusType\x12\x16\n\x0esplit_min_size\x18\x07 \x01(\x05\"$\n\rConsensusType\x12\x13\n\x0f\x43ONSENSUS_SPLIT\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ffn.inference.consensus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONSENSUSREQUEST']._serialized_start=94
  _globals['_CONSENSUSREQUEST']._serialized_end=354
  _globals['_CONSENSUSREQUEST_CONSENSUSTYPE']._serialized_start=318
  _globals['_CONSENSUSREQUEST_CONSENSUSTYPE']._serialized_end=354
# @@protoc_insertion_point(module_scope)
